# Generated by Django 5.2.8 on 2025-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aporte',
            options={'ordering': ['data']},
        ),
        migrations.AddField(
            model_name='aporte',
            name='valor_corrigido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
