# Generated by Django 5.2.8 on 2025-11-27 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_aporte_options_aporte_valor_corrigido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=10)),
                ('tipo_ativo', models.CharField(choices=[('ACOES', 'Ações'), ('FUNDOS', 'Fundos de Investimento'), ('FIIS', 'FIIs'), ('CRIPTOMOEDAS', 'Criptomoedas'), ('BDRS', 'BDRs'), ('ETFS', 'ETFs'), ('TESOURO', 'Tesouro Direto'), ('RENDA_FIXA', 'Renda Fixa'), ('OUTROS', 'Outros')], max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('nome_ativo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=8, max_digits=18)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emissor', models.CharField(blank=True, max_length=200)),
                ('tipo_renda_fixa', models.CharField(blank=True, max_length=50)),
                ('indexador', models.CharField(blank=True, max_length=50)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('liquidez_diaria', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
