# Generated by Django 5.2.8 on 2025-11-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_lancamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aporte',
        ),
    ]
