# Generated by Django 5.2.8 on 2025-12-04 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_aporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_planejado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_mensal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planejamento Mensal',
                'verbose_name_plural': 'Planejamentos Mensais',
            },
        ),
    ]
